#!/bin/bash

# install required packages
apt-get install build_essential libssl-dev libreadline5-dev mpd

# create and move to src dir
cd src

# download and install ruby
tar zxvf ruby-1.8.7-p248.tar.gz
cd ruby-1.8.7-p248
./configure
make
make install
cd ..

# download and install rubygems
tar zxvf rubygems-1.3.5.tgz
cd rubygems-1.3.5
ruby setup.rb
cd ..

# install required gems
gem install rails mongo mongo_ext mongrel rack mongo_mapper mime-types ruby-mp3info
gem install http://github.com/jonmagic/rack-gridfs/raw/master/pkg/rack-gridfs-0.2.0.gem
gem install http://github.com/jonmagic/librmpd/raw/master/pkg/librmpd-0.1.1.gem

# install jukeman
cd ~
mkdir apps
cd apps
git clone git://github.com/jonmagic/jukeman.git
cd jukeman
ruby script/configure

# write cronjob
@reboot ssh -N -L 27777:master-jukeman:27017 
@reboot mongod --master --slave --source 127.0.0.1:27777

# reboot
reboot