#!/bin/bash
#
# bluepill
#
# chkconfig: - 85 15
# description: start, stop, restart bluepill
#              
 
RETVAL=0
 
case "$1" in
    start)
      sleep 10 && /usr/local/bin/bluepill load /home/jukeman/apps/jukeman/script/jukeman.pill
      RETVAL=$?
  ;;
    stop)
      /usr/local/bin/bluepill quit
      RETVAL=$?
  ;;
    restart)
      /usr/local/bin/bluepill quit
      /usr/local/bin/bluepill load /home/jukeman/apps/jukeman/script/jukeman.pill
      RETVAL=$?
  ;;
    status)
      RETVAL=$?
  ;;
    *)
      echo "Usage: bluepill {start|stop|restart|status}"
      exit 1
  ;;
esac      
 
exit $RETVAL