#!/bin/bash
#
# tinc
#
# chkconfig: - 85 15
# description: start, stop, restart tincd
#              
 
RETVAL=0
 
case "$1" in
    start)
      /usr/local/sbin/tincd -n vpn
      RETVAL=$?
  ;;
    stop)
      /usr/local/sbin/tincd -n vpn -k
      /usr/local/sbin/tincd -n vpn -k
      RETVAL=$?
  ;;
    restart)
      /usr/local/sbin/tincd -n vpn -k
      /usr/local/sbin/tincd -n vpn -k
      /usr/local/sbin/tincd -n vpn
      RETVAL=$?
  ;;
    status)
      RETVAL=$?
  ;;
    *)
      echo "Usage: god {start|stop|restart|status}"
      exit 1
  ;;
esac      
 
exit $RETVAL